name: Package Project

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3

      - name: Install deps
        run: make deps

      - name: Linter
        run: make lint

      - name: Tests
        run: make test
